### ISSUE TITLE
RadioButtonGroup.getElement().setProperty method does not work

### ISSUE THREAD

**Issue by evrenism** [vaadin/vaadin-radio-button-flow#135] opened 2020-05-14 14:26 UTC
I add property to the RadioButtonGroup element as follows;
```
RadioButtonGroup<SampleClass> radioButtonGroup = new RadioButtonGroup<>();
radioButtonGroup.getElement().setProperty("column", "2");
```
I expect it to work like this;
`<vaadin-radio-group column = "2"> ... </vaadin-radio-group>`
But the setProperty method does not work.

**Comment by evrenism** [comment] 2020-05-15 09:00
A similar issue continues here; https://github.com/vaadin/vaadin-checkbox-flow/issues/147

**Comment by DiegoCardoso** [comment] 2020-05-15 11:12
Closing. It's not a bug, as explained here: https://github.com/vaadin/vaadin-checkbox-flow/issues/147#issuecomment-629162140

**Closed by DiegoCardoso** 2020-05-15 11:12 UTC
