### ISSUE TITLE
RadioButtonGroup not updated correctly via binder when component is opened in a dialog

### ISSUE THREAD

**Issue by TomRauchenwald** [vaadin/vaadin-radio-button-flow#162] opened 2020-03-17 08:13 UTC
In our app, we open dialogs to edit beans.
With Vaadin 15 (up to 15.0.2)/Flow 3.0.1 binding to a RadioButtonGroup doesn't work anymore, if the RadioButtonGroup is defined in a template and injected via @Id.

Here's a minimal example:

The bean:
```
public class Bean {
    String name;
    String kind;

    public Bean(String name, String kind) {
        this.name = name;
        this.kind = kind;
    }

    public String getName() {
        return name;
    }

    public String getKind() {
        return kind;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setKind(String kind) {
        this.kind = kind;
    }

        @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Bean bean = (Bean) o;
        return Objects.equals(name, bean.name) &&
                Objects.equals(kind, bean.kind);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, kind);
    }
}
```
In the view, we create three instances and put them in a grid.
```
@Route
@JsModule("views/main-view.js")
@Tag("main-view")
public class MainView extends PolymerTemplate<TemplateModel> {
    private final MainForm mainForm;

    @Id("grid")
    Grid<Bean> grid;

    public MainView(@Autowired MainForm mainForm) {
        this.mainForm = mainForm;

        grid.addColumn(Bean::getName);
        grid.addColumn(Bean::getKind);
        grid.setItems(
                new Bean("test bean 1", "A"),
                new Bean("test bean 2", "B"),
                new Bean("test bean 3", "C"));
        grid.setSelectionMode(Grid.SelectionMode.NONE);
        grid.addItemClickListener(cl -> openDialog(cl.getItem()));
    }

    private void openDialog(Bean bean) {
        mainForm.readBean(bean);
        new Dialog(mainForm).open();
    }
}
```
The form just declares a value set for the group and binds the bean:
```
@JsModule("views/main-form.js")
@Tag("main-form")
@Component
@Scope(DefaultListableBeanFactory.SCOPE_PROTOTYPE)
public class MainForm extends PolymerTemplate<TemplateModel> {
    @Id("name")
    TextField name;

    @Id("kind")
    RadioButtonGroup<String> kind;

    private final BeanValidationBinder<Bean> binder = new BeanValidationBinder<>(Bean.class);

    public MainForm() {
        kind.setItems("A", "B", "C");
        binder.forField(name)
                .bind("name");
        binder.forField(kind)
                .bind("kind");
    }

    public void readBean(Bean bean) {
        binder.readBean(bean);
    }
}
```
I would expect the form to display the kind that's shown in the grid every time i click on an item.
What's actually happening is that the value for kind will be set correctly the first time an item is clicked. On subsequent clicks the value will not change.

This does not happen if the form is not put in a dialog. So I'm not sure if this is a bug in RadioGroup, Dialog or flow itself, so I'm filing here. Hope this is ok.

Here's the project I used:
[test-radiogroup.zip](https://github.com/vaadin/flow/files/4342208/test-radiogroup.zip)

**Comment by caalador** [comment] 2020-09-23 12:33
Coming back around it seems that there is some issue with the `@Id` usage in dialog which makes PolymerTemplate binding in SimpleElementBindingStrategy return the old value.

Changing the MainForm to not map the radiobutton but only add it as an element to a slot will make the radio button behave as expected:

```java
    private RadioButtonGroup<String> kind;
    public MainForm() {
        kind = new RadioButtonGroup<>();
        kind.setItems("A", "B", "C");
        binder.forField(name)
                .bind("name");
        binder.forField(kind)
                .bind("kind");
        kind.addValueChangeListener(event -> {
            System.out.println("Value selected: " + event.getValue());
        });
        getElement().appendChild(kind.getElement());
    }
```

It would seem like there is some model data left somewhere on the that then updates the node properties to be the old ones on element bind.

**Comment by denis-anisimov** [comment] 2020-10-05 12:12
Steps to reproduce without Spring and without Binder:

Use skeleton starter
https://github.com/vaadin/skeleton-starter-flow

Replace `MainView`  with the content:

```
@Tag("main-form")
@JsModule("src/main-form.js")
public class MainView extends PolymerTemplate<TemplateModel>
        implements HasComponents {

    @Id("kind")
    private RadioButtonGroup<String> radioButtonGroup;

    public MainView() {
        radioButtonGroup = new RadioButtonGroup<String>();
        radioButtonGroup.setItems("a", "b", "c");

        NativeButton showDialog = new NativeButton("Open Dialog",
                event -> showDialog());
        add(showDialog);
    }

    private void showDialog() {
        radioButtonGroup.setValue("b");
        new Dialog(radioButtonGroup).open();
    }
}
```

Use this template for `main-form.js` :
```
import {html, PolymerElement} from '@polymer/polymer/polymer-element.js';
import '@vaadin/vaadin-radio-button/src/vaadin-radio-group.js';

class MainForm extends PolymerElement {
    static get template() {
        return html`
            <div>
                <vaadin-radio-group id="kind" colspan="2"></vaadin-radio-group>
            </div>
            <slot></slot>
        `;
    }

    static get is() {
        return 'main-form';
    }
}

customElements.define(MainForm.is, MainForm);
```

- open browser
- click the button
- select the radio button group in the Chrome inspector
- make sure the mouse pointer is inside the inspector
- Use console in the inspector to set the value: current value `"$0.value"` should be `"2"` , set it to `"1"`: `$0.value=1`.
- Check visually (don't do anything!) that RBG value is set to "a" (from the previous value "b").
- Move mouse pointer from inspector to the browser HTML view.
- In most cases the value in RBG is set to "b" on this move.

So some "focus" event or something trigger value change back unexpectadly.
This is caused by `vaadin-radio-button-group` web component on the client side since no any server side events happen on move.

**Comment by denis-anisimov** [comment] 2020-10-05 12:14
I cannot move it to `vaadin-radio-button`   repo for some reason. So I close it and create another one.

**Closed by denis-anisimov** 2020-10-05 12:14 UTC
Labels: BFP, Impact: Low, Severity: Major, bug, workaround

**Comment by denis-anisimov** [comment] 2020-10-05 12:22
https://github.com/vaadin/vaadin-radio-button/issues/166
